spring.application.name=MusicBooru

spring.datasource.url=jdbc:postgresql://localhost:6432/musicbooru
spring.datasource.username=musicbooru
spring.datasource.password=supersecretpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

garage.endpoint=http://localhost:3900
garage.access-key=GKead35a60462172a3f64436f8
garage.secret-key=cf2bafc0d06cd9d01aec597efd194c26c1eabf8caa4c2f0a961e9a34a3355ad8
garage.bucket-library=library
garage.bucket-artwork=artwork

logging.file.name=musicbooru.log
logging.level.com.example.musicbooru=DEBUG