spring.application.name=MusicBooru

spring.datasource.url=jdbc:postgresql://localhost:6432/musicbooru
spring.datasource.username=musicbooru
spring.datasource.password=supersecretpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=500MB

garage.endpoint=http://localhost:3900
garage.access-key=GK4c5425e0ce9240a1f48cd3dd
garage.secret-key=dcb1dd598fb7dafb698275161e5df01db430728ce4de4b47b3438b4a50e68ca0
garage.bucket-library=library
garage.bucket-artwork=artwork

logging.file.name=musicbooru.log
logging.level.com.example.musicbooru=DEBUG